### ISSUE TITLE
Please add a screen shot

### ISSUE THREAD

**Issue by unixorn** [rafa-wine/monsi_oh-my-zsh_theme#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I prefer to add themes with screen shots so that users can see what they look like without having to install them.

Thanks!

**Comment by rafa-wine** [comment]
Ready, excuse me for the delay.

**Comment by rafawine** [comment]
@unixorn. Ready, excuse me for the delay.
